In [ ]:
import numpy as np
import matplotlib.pyplot as plt

### create

In [16]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [27]:
a= np.ones(10)
a[0:4].fill(0)
a

array([ 0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,  1.,  1.])

### copy

### delete

In [1]:
a= np.array([[0, 0, 0, 0, 0, 0, 0, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])
a.shape

(7, 10)

In [2]:
np.delete(a, 2)

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
np.delete(a, 2, axis=1).T

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1, 0, 0],
       [1, 1, 1, 1, 1, 0, 0],
       [1, 1, 1, 1, 1, 0, 0],
       [1, 1, 1, 1, 1, 0, 0]])

In [30]:
b = np.arange(10)
np.insert(b,2 ,3)

array([0, 1, 3, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
int.max

AttributeError: type object 'int' has no attribute 'max'