In [2]:
import numpy as np
from numpy.linalg import det
from numpy.linalg import inv

1.矩阵点积

In [3]:
a = np.array([[1,2],[3,4]])
det(a)

-2.0000000000000004

2. 计算逆矩阵

In [4]:
inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

3. 计算矩阵积

In [5]:
b = np.array([[1,2,3],[3,5,1]])
np.dot(a,b)

array([[ 7, 12,  5],
       [15, 26, 13]])

In [6]:
np.sqrt(a)

array([[ 1.        ,  1.41421356],
       [ 1.73205081,  2.        ]])

In [9]:
np.square(a)

array([[ 1,  4],
       [ 9, 16]])