### random

In [1]:
import numpy as np

返回一个样本，具有标准正态分布。

In [4]:
np.random.randn(2,3)

array([[ 0.6072258 ,  1.83751911,  0.37267223],
       [-1.84998423, -0.60184147, -0.27691472]])

返回随机的整数，位于半开区间 [low, high)。
randint(low[, high, size])

In [9]:
np.random.randint(1,5, size = 100)

array([2, 2, 1, 3, 1, 4, 3, 2, 1, 1, 1, 2, 4, 2, 1, 1, 4, 4, 1, 2, 2, 3, 2,
       2, 1, 4, 3, 1, 3, 3, 4, 4, 2, 4, 2, 4, 1, 4, 2, 4, 1, 1, 4, 1, 4, 4,
       3, 1, 1, 3, 2, 2, 3, 1, 3, 2, 3, 1, 3, 1, 3, 3, 4, 3, 1, 3, 2, 3, 1,
       1, 4, 1, 3, 1, 1, 2, 2, 4, 1, 2, 1, 2, 4, 3, 1, 3, 2, 2, 1, 4, 3, 1,
       1, 3, 2, 1, 1, 3, 2, 3])

返回随机的浮点数，在半开区间 [0.0, 1.0)。
random_sample([size])

In [14]:
np.random.random_sample(4)

array([ 0.88502482,  0.34640158,  0.31136323,  0.80049671])

生成一个随机样本，从一个给定的一维数组
choice(a[, size, replace, p])

In [21]:
np.random.choice(np.arange(10), 6)

array([2, 5, 8, 1, 5, 1])

现场修改序列，改变自身内容。（类似洗牌，打乱顺序）
shuffle(x)

In [41]:
a = np.random.randn(10)
a

array([-0.26005001,  0.46942119,  0.06576205,  0.29396566,  1.42385803,
       -0.71585598, -1.06364163,  0.41707796, -0.04708961, -0.53590347])

In [51]:
np.random.shuffle(a)
a

array([ 0.41707796, -0.26005001,  0.46942119, -0.04708961,  1.42385803,
       -0.71585598, -0.53590347, -1.06364163,  0.29396566,  0.06576205])

In [52]:
np.floor(a)

array([ 0., -1.,  0., -1.,  1., -1., -1., -2.,  0.,  0.])

In [53]:
a

array([ 0.41707796, -0.26005001,  0.46942119, -0.04708961,  1.42385803,
       -0.71585598, -0.53590347, -1.06364163,  0.29396566,  0.06576205])