## Questions

all()需要所有都True,才返回true,有点像&&. any()只需要一个True, 就返回true,像||。 这一特点常用来做比较。

In [3]:
import numpy as np
o=np.array([False, True])
o.all()

False

In [4]:
o.any()

True

#### All()

In [5]:
np.all([[True,False],[True,True]], axis=0)

array([ True, False], dtype=bool)

In [6]:
np.all([[True,True],[True,False]], axis=0)

array([ True, False], dtype=bool)

In [7]:
np.all([[True,False],[True,True]], axis=1)

array([False,  True], dtype=bool)

In [8]:
np.all([[True,True],[True,False]], axis=1)

array([ True, False], dtype=bool)

In [9]:
np.all([[True,False],[True,True]])

False

In [10]:
np.all([[True,False],[True,False]])

False

In [11]:
np.all([[True,True],[True,True]])

True

In [12]:
np.all([True,-1])

True

#### Any()

In [13]:
np.any([[True, False], [False, False]], axis=0)

array([ True, False], dtype=bool)

In [14]:
np.any(np.nan)

True

#### nonzeros

nonzeros(a)返回数组a中值不为零的元素的下标，它的返回值是一个长度为a.ndim(数组a的轴数)的元组.
例如二维数组x,它的非零为x[0,0]=1, x[1,1]=2, x[2,0]=1, x[2,1]=1。所以nonzero的数组下表分别是(0,1,2,2)和(0,1,0,1)

In [16]:
x = np.array([[1,0,0], [0,2,0], [1,1,0]])
np.nonzero(x)

(array([0, 1, 2, 2]), array([0, 1, 0, 1]))

In [17]:
x[np.nonzero(x)]

array([1, 2, 1, 1])

#### numpy.where

where(condition,x,y)，根绝规则选择出元素，condition,x,y都是一样的结构，condition位置是true，则选x,否则选y。

In [18]:
np.where([[True, False], [True, True]], [[1, 2], [3, 4]], [[9, 5], [7, 6]])

array([[1, 5],
       [3, 4]])