### 资源加载

In [1]:
import numpy as np
from Lesson import Lesson
r = np.load('rubik/r_2018-51.npy')
lt = Lesson(True)

#### r 就是模型

In [48]:
r.shape

(3, 851, 9, 7)

#### 房间总数

In [49]:
np.sum(r)

42224.0

#### 总人数

In [50]:
np.sum(r[0]) * 4 + np.sum(r[1]) * 2 +  np.sum(r[2])

132003.0

#### 周几  (*)  数据比周几小一

In [51]:
day_num = 2 # 2是周三    0是周一   6是周日
np.sum(r[0,:,:,day_num]) * 4 + np.sum(r[1,:,:,day_num]) *2 + np.sum(r[2,:,:,day_num])

18689.0

#### 一周分布 room 1v4

In [52]:
np.sum(r[0], axis=0)

array([[   0.,    0.,    0.,    0.,    0.,  429.,  411.],
       [   0.,    0.,    0.,    0.,    0.,  427.,  409.],
       [   0.,    0.,    0.,    0.,    0.,  404.,  399.],
       [   0.,    0.,    0.,    0.,    0.,  401.,  397.],
       [   0.,    0.,    0.,    0.,    0.,  388.,  389.],
       [ 771.,  808.,  814.,  818.,  765.,  452.,  403.],
       [ 970., 1008.,  977.,  977.,  936.,  580.,  472.],
       [1116., 1129., 1097., 1093., 1057.,  728.,  607.],
       [ 896.,  945.,  910.,  898.,  876.,  659.,  586.]])

#### 一周分布room 1v2

In [53]:
np.sum(r[1], axis=0)

array([[  0.,   0.,   0.,   0.,   0.,  85.,  72.],
       [  0.,   0.,   0.,   0.,   0.,  94.,  83.],
       [  0.,   0.,   0.,   0.,   0.,  79.,  82.],
       [  0.,   0.,   0.,   0.,   0.,  72.,  62.],
       [  0.,   0.,   0.,   0.,   0.,  70.,  66.],
       [295., 297., 298., 255., 238.,  79.,  83.],
       [334., 331., 311., 285., 269., 110.,  81.],
       [361., 350., 314., 306., 275., 147., 101.],
       [314., 331., 290., 277., 267., 109., 100.]])

#### 一周分布room 1v1

In [54]:
np.sum(r[2], axis=0)

array([[  0.,   0.,   0.,   0.,   0., 101., 101.],
       [  0.,   0.,   0.,   0.,   0., 100.,  90.],
       [  0.,   0.,   0.,   0.,   0.,  99.,  96.],
       [  0.,   0.,   0.,   0.,   0., 105.,  94.],
       [  0.,   0.,   0.,   0.,   0.,  87.,  95.],
       [241., 258., 243., 234., 208.,  94.,  89.],
       [274., 281., 271., 246., 237., 137., 121.],
       [300., 302., 292., 279., 256., 184., 142.],
       [275., 277., 265., 249., 234., 154., 138.]])

In [10]:
a = [[0,0,0,0,0,1,1],[0,0,0,0,0,1,1],[0,0,0,0,0,1,1],[0,0,0,0,0,1,1],[0,0,0,0,0,1,1],
     [1,1,1,1,1,1,1],[2,2,2,1,1,1,1],[2,2,2,1,1,1,1],[1,1,1,1,1,1,1]]
b = np.array(a)

In [11]:
c = [[0,0,0,0,0,1,1],[0,0,0,0,0,4,4],[0,0,0,0,0,3,3],[0,0,0,0,0,3,3],[0,0,0,0,0,3,3],
     [4,4,4,4,4,4,4],[5,5,5,5,5,5,5],[6,6,6,6,6,6,6],[3,3,3,3,3,3,3]]
c = np.array(c)

In [42]:
r[0,10] = (r[0,10]/2).round()

In [47]:
r[0,10]

array([[ 0.,  0.,  0.,  0.,  0.,  4.,  4.],
       [ 0.,  0.,  0.,  0.,  0.,  5.,  4.],
       [ 0.,  0.,  0.,  0.,  0.,  4.,  4.],
       [ 0.,  0.,  0.,  0.,  0.,  4.,  4.],
       [ 0.,  0.,  0.,  0.,  0.,  4.,  3.],
       [ 6.,  7.,  7.,  8.,  7.,  4.,  4.],
       [10., 10., 10., 10.,  9.,  6.,  5.],
       [11., 12., 10., 10., 10.,  8.,  7.],
       [ 8.,  9.,  9.,  8.,  8.,  8.,  6.]])

#### 一周人数分布

In [12]:
np.sum(r[1], axis=0) * 2 + np.sum(r[0], axis=0) * 4 + np.sum(r[2], axis=0)

array([[   0.,    0.,    0.,    0.,    0., 2078., 2097.],
       [   0.,    0.,    0.,    0.,    0., 2072., 2208.],
       [   0.,    0.,    0.,    0.,    0., 2029., 2204.],
       [   0.,    0.,    0.,    0.,    0., 1901., 2031.],
       [   0.,    0.,    0.,    0.,    0., 1901., 2000.],
       [4673., 4811., 4446., 4325., 3938., 2453., 2040.],
       [5577., 5724., 5213., 5245., 4824., 3449., 2657.],
       [6342., 6650., 6144., 6039., 5757., 4152., 3628.],
       [4892., 5475., 4591., 4551., 4983., 4182., 4256.]])

In [13]:
def getLesson(course, lesson, r):
    lesson_id = lt.getLesson(course, lesson)
    print('lesson id: %d' % lesson_id)
    print('---  总数 %d ---' % np.sum(r[0][lesson_id] + r[1][lesson_id] + r[2][lesson_id]))
    print(r[0][lesson_id] + r[1][lesson_id])
    print('--- 4人班 %d ---' % np.sum(r[0][lesson_id]))
    print(r[0][lesson_id])
    print('--- 2人班 %d ---' % np.sum(r[1][lesson_id]))
    print(r[1][lesson_id])

#### 查看任意课程需要房间数
 + 查看L7_3 
 + 修改如下 course, lesson=(7,3) 
 + 只需要修改括号中的数字

In [14]:
course, lesson =15, 1
getLesson(course, lesson, r)

NameError: name 'course_id' is not defined

#### Lesson ID 转课程名称

In [ ]:
lesson_id = 227
lt.get_course_lesson_name(lesson_id)

#### 删除某些课

In [ ]:
def removeRooms(r, indexs):
    for r4 in r[0]:
        for index in indexs:
            r4[index[0], index[1]] = 0
    for r4 in r[1]:
        for index in indexs:
            r4[index[0], index[1]] = 0